#!/usr/bin/env python3
"""Generate compact 5x7 Cyrillic+ASCII font for AVR (column bitmap, 5 bytes/glyph)."""

from __future__ import annotations

import os
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

W, H = 5, 7
ASCII_COUNT = 0x7F - 0x20 + 1  # 95
CYR_UPPER = [chr(c) for c in range(0x0410, 0x0430)] + ["\u0401"]  # А-Я + Ё
CYR_LOWER = [chr(c) for c in range(0x0430, 0x0450)] + ["\u0451"]  # а-я + ё
ALL_CHARS = [chr(c) for c in range(0x20, 0x7F)] + CYR_UPPER + CYR_LOWER


def find_font() -> str:
    candidates = [
        r"C:\Windows\Fonts\arial.ttf",
        r"C:\Windows\Fonts\segoeuib.ttf",
        r"C:\Windows\Fonts\tahoma.ttf",
        r"C:\Windows\Fonts\calibri.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/TTF/DejaVuSans.ttf",
    ]
    for path in candidates:
        if os.path.isfile(path):
            return path
    raise FileNotFoundError("No TTF font found for glyph generation")


def render_glyph(ch: str, font: ImageFont.FreeTypeFont) -> list[int]:
    img = Image.new("1", (W, H), 0)
    draw = ImageDraw.Draw(img)
    draw.text((0, -1), ch, font=font, fill=1)
    cols: list[int] = []
    for x in range(W):
        col = 0
        for y in range(H):
            if img.getpixel((x, y)):
                col |= 1 << y
        cols.append(col)
    return cols


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    out_path = root / "src" / "font_cyrillic.h"

    font = ImageFont.truetype(find_font(), 7)
    bitmaps: list[int] = []
    for ch in ALL_CHARS:
        bitmaps.extend(render_glyph(ch, font))

    lines = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by tools/gen_cyrillic_font.py — do not edit by hand.",
        f"// Glyphs: ASCII 0x20..0x7E ({ASCII_COUNT}), Cyrillic upper+lower incl. Ё/ё.",
        f"// Format: 5 columns x 7 rows, 5 bytes per glyph, bit y = row from top.",
        "",
        f"constexpr uint8_t kFontGlyphCount = {len(ALL_CHARS)};",
        "constexpr uint8_t kFontGlyphWidth = 5;",
        "constexpr uint8_t kFontGlyphHeight = 7;",
        "constexpr uint8_t kFontGlyphBytes = 5;",
        "constexpr uint8_t kFontAsciiCount = 95;",
        "constexpr uint8_t kFontCyrUpperCount = 33;",
        "constexpr uint8_t kFontCyrLowerCount = 33;",
        "",
        "static const uint8_t kFontBitmaps[] PROGMEM = {",
    ]

    for i in range(0, len(bitmaps), 10):
        chunk = bitmaps[i : i + 10]
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(ALL_CHARS)} glyphs, {len(bitmaps)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
